### ISSUE TITLE
Support ACI Simulator??

### ISSUE THREAD

**Issue by yohanoh** [F5Networks/f5-aci-servicecenter#108]
Hello. 

Does this app also support to operate on aci simulator ? (or only real aci?)

Actually, I already test the app on aci simulator (4.2-6o, 5.1-4c), but not work..

**Comment by ericzji** [comment]
Hi, 
This app is built to run in real Cisco ACI. Cisco ACI Simulator does not allow us to install this DC App Cener app, so we can not run the F5 app directly there.

Above said, we do build separate tools to support the app for Cisco ACI Simulator. This is the way we used to build the Cisco dCloud ACI service center lab.
https://dcloud-docs.cisco.com/c/r/dcloud-docs/sites/en_us/DCV/cisco_aci_with_f5_servicecenter_lab_v2/b_aci_with_f5_servicecenter_v2.html?dc=rtp

Please take a look to see if you can leverage the above dCloud Lab. If you need to run it in your own ACI simulator, please reach out to F5/us, and we can look at your requirement.
thanks
-Eric
