### ISSUE TITLE
Keep need to re-login big-ip credential in F5 ACI Service Center App

### ISSUE THREAD

**Issue by Prachachart** [F5Networks/f5-aci-servicecenter#124]
Dear Expert,

I testing ACI-Service Center and found out after just few minute - if we go to any page in app will ask to re-login with F5 credential again. Did we have a way to fix or config timeout parameter kind of that is possible?

Thanks.

**Comment by jyeung-F5** [comment]
It appears to be a browser issue.  Ok to close.
