### ISSUE TITLE
BIG-IP supported version for ACI service graph.

### ISSUE THREAD

**Issue by LeonFaith** [F5Networks/f5-aci-servicecenter#54]
Hi F5,

I would like to purchase a liences for ACI service graph. 
This is which I have plan to purchase. 
BIG-IP Virtual Edition Lab License (v. 18.x) - license - 10 Mbps
Mfg.Part: F5-BIG-VE-LAB-V18

Please let me know if this one supported ACI service graph, if not which license I should purchase??

**Comment by payalsin** [comment]
Please re-open issue if you still have queries.
