### ISSUE TITLE
Device Package for ACI 4.2.1

### ISSUE THREAD

**Issue by saz6710** [F5Networks/f5-aci-servicecenter#55]
Hi
Could you please provide me link to download Device Packages for F5 Vedition. I am using APIC 4.2.(1).
link to documents would be great.

thanks
shahid

**Comment by payalsin** [comment]
Hi Shahid,

F5 integration with ACI is not based on the device package. The integration is based on the APIC App Center:  https://dcappcenter.cisco.com/f5-aci-servicecenter.html

Using the link above you can download the App and upload it to the APIC. There is also pointer to the user guide as well as a Video explanation of the integration in the link above.

The App will work with your version of APIC - 4.2(1)

Thanks
Payal

**Comment by saz6710** [comment]
Thanks Payal. I will try it and give try.

 

Shahid

**Comment by saz6710** [comment]
Hi Payal

 

Is there document there for configuration and deployment?

 

Thanks

Shahid

**Comment by payalsin** [comment]
Hi Shahid,

User guide: https://clouddocs.f5.com/f5-aci-servicecenter/latest/

Thanks
Payal

**Comment by payalsin** [comment]
Please re-open issue if you still have queries.
