### ISSUE TITLE
Poling No Information on Service Center 2.3 and ACI 4.2(2f)

### ISSUE THREAD

**Issue by kwyjibo19** [F5Networks/f5-aci-servicecenter#70]
I have tried to install both service center 2.2 and 2.3 but got no information from my BIG-IP device.
Is there any pre-requisite before installing the app on ACI? I have followed this documentation.
https://clouddocs.f5.com/f5-aci-servicecenter/latest/

Is provisioning an L4-L7 device required? If yes, how? Since we don't have service package anymore.

**Comment by payalsin** [comment]
Hi @kwyjibo19 I had a follow up question.I am assuming you are able to login to the BIG-IP.

When you say no information from the BIG-IP, are you talking about the visibility use-case and if yes then which table are you referring, the vlan/vip or node table

To get information from the BIG-IP yes there needs to be configuration on the BIG-IP
1) Visibility: vlan table - A VLAN is present on the BIG-IP that is also present on the APIC as part of a service graph
2) Visibility: vip/node tables - Only those nodes (and the associated VIPs) will show up in the association table that are learned by the APIC fabric

The BIG-IP device can be provisioned via the Application
1) L2-L3 tab can be used to configure vlan/self-ip etc.
2) L4-L7 tab can be used to configure VIP/Pools/Nodes etc. either be using a template or by passing the entire configuration as JSON payload


Details of each use case is present here: https://clouddocs.f5.com/f5-aci-servicecenter/latest/
Following Videos might be helpful as well: tinyurl.com/F5ACIServiceCenterVideos

If you are still having trouble do let us know. You can email us directly as well: f5_aci_app_support@f5.com

**Comment by payalsin** [comment]
Please re-open issue if you still have queries.
