### ISSUE TITLE
Error deploying AS3 config  - from ACI App

### ISSUE THREAD

**Issue by chungyu2** [F5Networks/f5-aci-servicecenter#74]
Hi 

I am trying to use the Advance Tab to deploy an AS3 config 0- but I getting an error message that references the serverSSL profile 

Error from BIG-IP: /web_services/drupal_vs/Application1VIP/serverTLS: should be object

I have verified that the profile is indeed an existing object.

Below is my AS3

{
              "class": "Application",
              "template": "generic",
              "Application1VIP": {     
                             "class": "Service_HTTPS",
                             "virtualAddresses": [
                                           "132.216.91,12"
                             ],
                             "virtualPort": 443,
                             "profileTCP": {
                                            "bigip": "/Common/mptcp-mobile-optimized"
              },
                             "profileHTTP": {
                                            "bigip": "/Common/mgu_http_basic"                                                   
                            },
                             "allowVlans": [{
                                           "bigip": "/Common/F5-DEV-QA-Out"    
                             }],
                             "pool": "web_pool",
                             "clientTLS": [{
                                           "bigip": "/Common/mgu_default_serverssl"                                        
                             }],
                             "serverTLS": [{
                                           "bigip": "/Common/mgu_star_it_clientssl"                                         
                             }]
              },
              "web_pool": {
                             "class": "Pool",
                             "monitors": [
                                           "http"
                             ],
                             "members": [{
                                           "servicePort": 80,
                                           "serverAddresses": [
                                                          "172.16.10.11"
                                                                   ]
                             }]
              }
}

**Comment by payalsin** [comment]
@chungyu2 - please update to the lastest AS3 version and try the declaration again:
https://github.com/F5Networks/f5-appsvcs-extension/releases (version 3.19.1)

**Comment by payalsin** [comment]
Please re-open issue if you still have queries.
