### ISSUE TITLE
L3-L4 Network setting (network stitching) different BIG_IP partion

### ISSUE THREAD

**Issue by Hoviktor84** [F5Networks/f5-aci-servicecenter#79]
Hi, 
I would like to manage the Selfip,VLAN,GW with the F5-ACI-ServiceSenter on different route-domain, different partion such as 0/common. How can I do that. 
Thanks, 
Viktor

**Comment by payalsin** [comment]
Hi @Hoviktor84 , right now we have support for deploying self-IP, vlan and default gateway in the common partition with default route domain.

It would be great if we can get on a call to understand your use case in more detail. We would like to gather requirements and look into how we can incorporate them within the ServiceCenter. Please send an email to 'f5_aci_app_support@f5.com' and we can co-ordinate on setting up a call.

Thanks
