### ISSUE TITLE
VLAN-Group is supported?

### ISSUE THREAD

**Issue by azayed777** [F5Networks/f5-aci-servicecenter#87]
Dears

My LTM is already configured with VLAN-Groups, is it supported in the app to read, create or modify VLAN-Groups?

Regards
Ahmed

**Comment by payalsin** [comment]
Hi @azayed777 VLAN-groups is not supported through the App. However It would be great if we can get on a call to understand your use case in more detail. We would like to gather requirements and look into how we can incorporate them within the ServiceCenter application. Please send an email to 'f5_aci_app_support@f5.com' and we can co-ordinate on setting up a call.

Thanks
